[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
rquickjs.workspace = true
futures-lite.workspace = true
async-channel.workspace = true
futures-channel.workspace = true
futures-executor.workspace = true

[lints]
workspace = true
